ftplugin/orgmode/plugins/Agenda.py

Removing '-1' fixes the following error
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/ccc/home/gsaenger/.vim/bundle/vim-orgmode/ftplugin/orgmode/plugins/Agenda.py", line 171, in list_next_week
bufname = os.path.basename(vim.buffers[h.document.bufnr - 1].name)
ValueError: number must be greater than zero

Fix ValueError

---

ftplugin/orgmode/plugins/Export.py

According to the documentation in http://orgmode.org/manual/Exporting.html the function names are different for exports to HTML/LaTeX/PDF.

make exports work with emacs 24.4

---

syntax/org.vim

- Without this fix, all #+BEGIN_* blocks are not
correctly highlighted; this fix just allows whitespace
to occur before the #+BEGIN blocks, which is quite
common in documents.

[SYNTAX] Fix syntax for #+BEGIN_* blocks

---

doc/orgguide.txt

- If not compiled with +conceal, shortening links
will not work. To compile with +conceal, choose
at least --with-features=big (or --with-features=huge).
I was unable to find another switch such as --enable-conceal.

[Doc] Added a note on +conceal and links

---

ftplugin/orgmode/plugins/Todo.py

With things like NERDTree open, the interactive todo jumps back to the wrong window and therefore doesn't work.  This goes back to the correct window (previous one) before doing the TODO change.

Return to right window before setting todo.

---

ftplugin/orgmode/liborgmode/checkboxes.py
ftplugin/orgmode/plugins/EditCheckbox.py

Fixed issue #209 by requiring at least one child checkbox to have non-`None` status for the subtree of a checkbox to be considered a checkbox list rather than plain list.

Checkbox issue#209

---

doc/orgguide.txt

You must use mattn/calendar-vim from GitHub.  Change orgguide.txt to reflect this.

The vimscripts calendar.vim does *not* have :CalendarH. 

---

ftplugin/orgmode/plugins/EditCheckbox.py
ftplugin/orgmode/vimbuffer.py

A fix for issue #213. Actually I don't like how it looks. But I don't know how to solve it more elegantly. We should probably delete this fix once neovim fixed its issue.

Neovim current.buffer[last_line] `out of bound` issue #213

---

doc/orgguide.txt
ftplugin/orgmode/plugins/Export.py

This adds functionality to export PDF as 'beamer'-class
Added:
- `<localleader>eb`
- `:OrgExportToBeamerPDF`
- Documentation for said changes
Not added: `org-beamer-export-as-latex` since I didn't want to change too much and I'm not "fluent" in python

added support for org-beamer-export-to-pdf

---

ftplugin/orgmode/plugins/TagsProperties.py

In Neovim, FileType autocmds are triggered on every buffer change. As a
result, this plugin would declare duplicate InsertLeave handlers every
time the user switched into a .org buffer.

Avoid duplicate InsertLeave handlers

---

syntax/org.vim

- For instance, internal links can have the following form:
[[#LINK_NAME]] and [[#LINK_NAME][DESCRIPTION]].
In the first case, #LINK_NAME was always displayed; but
the # should be removed (concealed). This patch does that.

[Syntax] Hyperlinks will now conceal the # (intern. links)

---

ftplugin/orgmode/liborgmode/orgdate.py
tests/test_liborgdate_parsing.py

Without the re.UNICODE option the patterns do not match dates with accented
characters like "Sáb", that can be generated depending on the user's locale

Matching dates with UTF-8 characters

---

ftplugin/orgmode/liborgmode/orgdate.py
tests/run_tests.py
tests/test_liborgdate_utf8.py

This fixes errors raised when opening the week agenda view and dates include UTF-8 characters like **á**
Probably first lines of python ever written by me, so excuse any gross misuses of best-practices

Handling UTF-8 characters on stftime

---

syntax/org.vim
syntax/orgagenda.vim

Vim's \a does not match accented alphabet characters like á. With \k both the
accented version and the regular one are matched.
For help with \k please refer to iskeyword
With this change, dates like <2016-05-07 Sáb> are highlighted properly

Using \k instead of \a when matching dates

---

CHANGELOG.org
ftplugin/orgmode/liborgmode/headings.py
tests/test_vimbuffer.py

There are several reasons for this.
* I don't see the point of forcing recognized keyword to be upper case in the
first place.
* Syntax highlighting & keyword recognition will be according to user defined
keyword list. If user defined lower-case keyword, those keywords will not be
properly highlighted or recognized after being forcefully uppercased. It's
hampering user experience.
* Judging from test, it seems the intension of forceful uppercase conversion is
designed to change user inputted lower-case keyword to upper case. It's
poorly designed, because the lower case input won't be recognized as keyword
in the first place. Hence the `upper()` function was actually never take any
effect. But even if it functions as it should. Say, user defined a keyword in
UPPER case, and typing in a …

Don't force Keyword to upper case

---

ftplugin/orgmode/_vim.py

Hi!
I ran into an issue when promoting a header if it contains a plain list (with or without checkboxes). While trying to figure out the cause, I found a way to fix it, but I'm not sure if this is the proper way to fix it, so please reject this PR if it's not :). The issue is as follows. Say I have the following org file:
* Header 1
** Header 2
- item 1
- item 2
- item 3
- item 4
- item 5
- item 6
Now, if I promote _Header 2_ using `<<`, I get the following file:
* Header 1
* Header 2
- item 1
- item 2
- item 3
- item 4
- item 5
- item 6
Depending on the number of items, the result will be different.
I used git bisect to find the commit where this behaviour started. I found that prior to commit 0baf1792d7de805b19e67f0b094926a988c9ca6f, it worked fine. After this commit, things started …

Plain-list alignment issue after promotion of header

---

ftplugin/orgmode/plugins/TagsProperties.py

I introduced this bug when I did conversion from filter() to list comprehension

fix bug for tag searching

---

doc/orgguide.txt

We changed the default for `g:org_indent` to `0`.

Update doc according to changed default

---

doc/orgguide.txt

Add hint to doc because the fraction feature (`[/]` or `[%]`) does not work with task status (e.g. `TODO`/`DONE`) yet.

Add hint in doc for "not fully implemented" feature

---

ftplugin/orgmode/liborgmode/dom_obj.py

As stated in [the documentation](https://docs.python.org/3/library/re.html#re.LOCALE), from Python 3.6 onwards `re.LOCALE can be used only with bytes patterns`. The suggested fix is to use re.UNICODE instead so I've just removed re.L flags from str patterns.
Fixes #265 and #263

Remove re.LOCALE flag from str patterns

---

CHANGELOG.org

This is a PR to release a new version of vim-orgmode.
I've added a couple of missing pull requests to the changelog (#222, #266). Also, I've tried to unify the notation in the changelog (for this release only though). "PR #xyz" for merged pull requests, "closes #xyz" for closed issues, since these seemed the most common.

Update Changelog for version 0.6.0

---

.travis.yml
README.org

Have a nice overview of the code coverage, for a preview [click here](https://codecov.io/gh/Psirus/vim-orgmode/branch/coverage). This is much clearer than having to look at the Travis output, we can track the progress over time and, as you can see, pull requests will get an automatic report on whether they increase or decrease coverage. Plus we get a nice badge.

Codecov integration

---

doc/orgguide.txt

I felt that I needed a specific example of how to install vim-orgmode using the plugin manager, so I added a specific example to the document.
#285

Upload in document how to install using dein.vim and vim-plug

---

ftplugin/org.vim

I noticed that the day "Fri" is hardcoded into the function CalendarAction in org.vim.
I changed it so that it instead puts the actual day there
Before (notice I select a wednesday but it says Fri):
After:
Thanks!

Fix hardcoded Fri in calendar date picker

---

ftplugin/org.vim
ftplugin/orgmode/_vim.py

I noticed that if I hit ctrl-c in the calendar picker, after getting the prompt to modify the date, I get an uncaught exception (See the gif).
before:
after:
I changed the code to catch the exception and return None.
Thank you.

fix ctrl-c on calendar insert message causing uncaught exception

---

ftplugin/orgmode/liborgmode/orgdate.py
ftplugin/orgmode/plugins/Agenda.py
ftplugin/orgmode/plugins/Date.py
ftplugin/orgmode/plugins/EditStructure.py
ftplugin/orgmode/plugins/Hyperlinks.py
ftplugin/orgmode/plugins/TagsProperties.py

Closes: #290.
It'd likely also be great if you ran your tests with `PYTHONWARNINGS=default`, to ensure no future ones are introduced, it's easy to make the mistake when the warnings are being hidden. You might also consider using a test runner rather than what you have in `run_tests`. I didn't make either of those changes, but if you're up for them I can possibly send a follow up PR.

Fix all the invalid escape sequences.

---

syntax/org.vim

tl;dr
replaces any char matching `\W` to `"u" . char2nr(_matched_char_)` when calling `highlight`
which allows for decorated unicode todo keywords
------------
When defining a face for todo keyword, the `highlight` command is used internally with the new keyword as a part of the new name.
For example, when we want 'TODO' to be yellow we might define
```
let g:org_todo_keyword_faces = [['TODO', ':foreground yellow']]
```
For the above command `vim-orgmode` calls
```
highlight org_todo_keyword_face_TODO term=standout ctermfg=0 ctermbg=6 guifg=Blue guibg=Yellow  ctermfg=yellow guifg=yellow
```
If we were to define a new keyword that contains non-ASCII characters, `vim-orgmode` would try to use this non-ASCII word as a part of the highlight group name.
With these keywords and faces:
```
let …
```

Replace non-ASCII chars with their numeric value in highlight group names

---

doc/orgguide.txt

While following orgguide.txt, I found there's a missing quotation mark in org_agenda_files.
I can't find a contribution guide so if I missing some progress please tell me.

Add missing quotation mark in orgguide.txt

---

ftplugin/org.vim

Otherwise a "cannot import orgmode", "cannot find orgmode.ORGMODE" chain of errors is thrown on startup if you have `$HOME/.vimrc/bundle/*/` in your path.

[FIX] Correctly deal with wildcards in Vim path

---

doc/orgguide.txt

As far as I can tell, the variable is called `org_tags_column`.

Fix name of org_tags_column variable in guide

---

syntax/org.vim
syntax/orgtodo.vim

The configured 'org_todo_keywords' are subject to spellcheck. In
languages other than English, the spellchecker may not consider those
words to be spelled correctly. As a result, the spellchecker incorrectly
and annoyingly flags these words as misspelled. This patch removes the
keywords in the 'org_todo_keywords' from the province of the
spellchecker.
Issue #333

Feature: Exclude 'todo' keywords from spellcheck

---

ftplugin/orgmode/plugins/Export.py

A fix for issue #279. The bug is fully fixed compared to PR #283.

Fix export error messages encoding issues #279

---

ftplugin/orgmode/plugins/Agenda.py
ftplugin/orgmode/py3compat/py_py3_string.py
syntax/org.vim

*Issue*: If items in a file don't have `TODO`, `DONE`, etc keywords, that is, have a form `<date> title`, like `tl1` below:
```
* <2022-02-21 Mon> tl1
* TODO <2022-02-22 Tue> tl3
```
.. then they appear with `None` in the view "Time line for the current buffer":
```
None <2022-02-21 Mon> tl1
TODO <2022-02-22 Tue> tl3
```
*Solution*: this commit removes these `None`s:
```
<2022-02-21 Mon> tl1
TODO <2022-02-22 Tue> tl3
```
gVim now supports it

Two improvements
